module.exports = {
    stock_count_node: 'stock_count',
    expiry_time_node: 'expiry_time',
    zero_sales_count_node: 'zero_sales_count',
    last_scanned_count_node: 'last_scanned_count',
    dispenser_status_node: 'dispenser_status',
    load_time_node: 'load_time',
    dispenser_queue_node: 'dispenser_queue',
    dispense_id_node: 'dispense_id',
    bill_no_node: 'bill_number',
    expiry_slots_node: 'expiry_slots',
    plc_config_node: 'plc_config',
    outlet_config_node: 'outlet_config',
    start_of_day_flag: 'start_of_day',
    test_mode_flag: 'test_mode',
    stop_orders_flag: 'stop_orders',
    unscanned_slots_node: 'unscanned_slots',
    last_load_info_node: 'last_load_info',
    last_load_tmp_node: 'last_load_info_tmp',
    loading_issue_items_node: 'loading_issue_items',
    reconcile_stock_count_node:'reconcile_stock_count',
    barcode_comparision: 'barcode_comparision',
    po_details_node: 'po_details',
    reconcile_remarks_node: 'reconcile_remarks',
    session_time_node:'outlet_session_timings'
};
